server:
  port: 9696
  
Spring:
    application:
      name: CLOUD-GATEWAY
      
    cloud:
     gateway:
      routes:
      - id: SIGN-UP
        uri: lb://SIGN-UP
        predicates:
         - Path=/api/users/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
         - Path=/product/**
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
  
        